apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    app: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000  # Accessible via minikube IP on port 30000
    protocol: TCP
    name: http